### ISSUE TITLE
[Question] Ultrawide pixelated

### ISSUE THREAD

**Issue by Tealk** [hmlendea/gfn-electron#148]
### Describe the bug

With Ultrawide monitors, the display is very pixelated, can you do something about it?

### To Reproduce

1) Starte GFN
2) Starte ein Spiel

### Screenshots

![2022-06-04_12-32](https://user-images.githubusercontent.com/12276250/171995436-fc6533fc-085d-4417-a87e-eb37f9ca44e0.png)

### Operating System

EndeavourOS

### Desktop Environment

Gnome 42

### Display Server

Wayland

### Installation method

flatpack

### Version

1.7.0

### Is this a fresh install of the app or an update from a past version?

1.1.11

### Did this issue appear right away upon installation/updating, or spontaneously?

Yes

**Comment by hmlendea** [comment]
What is your monitor resolution exactly?

**Comment by Tealk** [comment]
The monitor has a resolution of 3440x1440

I often don't have much choice in games:
![image](https://user-images.githubusercontent.com/12276250/172200463-542b3cd1-683a-4c8c-8544-58bae2236daf.png)

**Comment by hmlendea** [comment]
GFN renders at a maximum of 1920x1080.

By the looks of it, your game runs at 1920x1200, which GFN downscales to 1920x1080 and then is upscaled to 3440x1440 to fit your monitor.

(Ok, the exact image resolutions after up/down scaling will be different because of the difference in the aspect ration, and black bars will be used to fill the screen; but you get the idea)

So, because the image is downscaled and then upscaled, the quality will be very bad. I would suggest setting the games to 1920x1080.
I know it's still not going to look very good, but because of GFN limitations, it's the best we can do.

**Comment by Tealk** [comment]
It's still not that really sharp
![image](https://user-images.githubusercontent.com/12276250/172444167-d01b649f-c272-440b-a61a-228f8836a6dd.png)

**Comment by hmlendea** [comment]
Yep. That looks about right. It's never going to look sharp until Nvidia uncaps the streaming resolution.
