### ISSUE TITLE
Adding Discord Rich Presence

### ISSUE THREAD

**Issue by OnikenX** [hmlendea/gfn-electron#21]
Just something to consider.

**Comment by hmlendea** [comment]
Could you please elaborate a bit more?

**Comment by baptiste0928** [comment]
Hello ! 👋 
I also think it would be a good addition, so I will clarify what it is about.

Rich Presence allows you to display more **detailed information on your Discord profile than a simple "playing at"**. It is possible to add text, images and even buttons to join someone else's game. The GeForce Now for Windows application already takes advantage of this:

![](https://user-images.githubusercontent.com/22115890/100417472-4b77f800-3081-11eb-9898-0b83c4fff84e.jpg)

It would be nice to add the same to this application, with why not custom images for some games.

**Useful links :**
- [Discord Developers documentation about Rich Presence](https://discord.com/developers/docs/rich-presence/how-to)
- [Unofficial npm package](https://www.npmjs.com/package/discord-rpc)

**Comment by hmlendea** [comment]
I will try to look into this once I get a little bit more free time to tinker with it.
However, from what I've investigated so far, I don't know if I will be able to (reliably) set images. Since this app is just a wrapper over the base version, I don't have access to the inner workings of GFN and I can only rely on the window titles (which is the game's name).

But I do agree it would be a really sweet feature to have.

**Comment by dubfib** [comment]
https://npmjs.com/package/discord-rpc
^^^ great place to start

**Comment by dubfib** [comment]
#119
